export default {
    Text: '文本',
    Autocomplete: '选择',
    Boolean: '布尔类型',
    NullableBoolean: '可以为空布尔类型',
    CheckboxGroup: '复选框',
    Date: '日期',
    Disabled: '不可编辑',
    // File:'文件',
    // Image:'图片',
    LongText: '长文本',
    Number: '数字',
    RadioButtonGroup: '单选框',
    ReferenceArray: '引用多选',
    Reference: '引用类型',
    RichText: '富文本',
    SelectArray: '多选',
    // Select:'选择',
}