server:
  port: 8080

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@ds036967.mlab.com:36967/easyadmin1
      database: easyadmin1