server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@ds161443.mlab.com:61443/easyadmin
#      uri: mongodb://localhost:27017
#      database: easyadmin-sys
      database: easyadmin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.24.7.29:3306/financial_cf_credit_icr
    username : root
    password : 123456

easyadmin:
  checkforapply: false