server:
  port: 8080

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

spring:
  data:
    mongodb:
      uri: mongodb://423ae41f319e4:d839c0d1101b4@192.168.1.98:30294/c68a42ecfc7c4
      database: c68a42ecfc7c4